<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PlayersSeeder extends Seeder
{
    public function run()
    {
        // Truncate the table before seeding to start fresh
        DB::table('players')->truncate();

        // Define the data to be inserted
        $players = [
            ['id' => 1, 'name' => 'Litton Das', 'image' => NULL, 'team_id' => 1, 'role' => 'WK Batsman', 'batting_style' => 'Right handed', 'bowling_style' => 'N/A', 'born' => '1990-02-28 00:00:00', 'biography' => 'player', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 2, 'name' => 'Tamim Iqbal', 'image' => NULL, 'team_id' => 1, 'role' => 'Batsman', 'batting_style' => 'Left handed', 'bowling_style' => 'N/A', 'born' => '2023-08-30 00:00:00', 'biography' => 'Tamim Iqbal', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 3, 'name' => 'Rony Talukdar', 'image' => NULL, 'team_id' => 1, 'role' => 'Batsman', 'batting_style' => 'Right handed', 'bowling_style' => 'N/A', 'born' => '2023-08-16 00:00:00', 'biography' => 'Rony Talukdar', 'status' => 0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 4, 'name' => 'Shakib Al Hasan', 'image' => NULL, 'team_id' => 1, 'role' => 'Batting AllRounder', 'batting_style' => 'Left handed', 'bowling_style' => 'Left arm spin', 'born' => '2023-08-01 00:00:00', 'biography' => 'Shakib Al Hasan', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 5, 'name' => 'Mushfiqur Rahim', 'image' => NULL, 'team_id' => 1, 'role' => 'WK Batsman', 'batting_style' => 'Right handed', 'bowling_style' => 'N/A', 'born' => '2023-08-30 00:00:00', 'biography' => 'Mushfiqur Rahim', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 6, 'name' => 'Mahmudullah', 'image' => NULL, 'team_id' => 1, 'role' => 'Batting AllRounder', 'batting_style' => 'Right handed', 'bowling_style' => 'Right arm spin', 'born' => '2023-08-01 00:00:00', 'biography' => 'Mahmudullah', 'status' => 0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 7, 'name' => 'Mehidy Hasan Miraz', 'image' => NULL, 'team_id' => 1, 'role' => 'Bowling AllRounder', 'batting_style' => 'Right handed', 'bowling_style' => 'Right arm spin', 'born' => '2023-08-01 00:00:00', 'biography' => 'Mehidy Hasan Miraz', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 8, 'name' => 'Towhid Hridoy', 'image' => NULL, 'team_id' => 1, 'role' => 'Batsman', 'batting_style' => 'Right handed', 'bowling_style' => 'N/A', 'born' => '2023-08-30 00:00:00', 'biography' => 'Towhid Hridoy', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 9, 'name' => 'Ebadot Hossain', 'image' => NULL, 'team_id' => 1, 'role' => 'Bowler', 'batting_style' => 'Right handed', 'bowling_style' => 'Right arm pace', 'born' => '2023-08-01 00:00:00', 'biography' => 'Ebadot Hossain', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 10, 'name' => 'Nasum Ahmed', 'image' => NULL, 'team_id' => 1, 'role' => 'Bowler', 'batting_style' => 'Left handed', 'bowling_style' => 'Left arm spin', 'born' => '2023-08-16 00:00:00', 'biography' => 'Nasum Ahmed', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 11, 'name' => 'Taijul Islam', 'image' => NULL, 'team_id' => 1, 'role' => 'Bowler', 'batting_style' => 'Left handed', 'bowling_style' => 'Left arm spin', 'born' => '2023-08-10 00:00:00', 'biography' => 'Taijul Islam', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 12, 'name' => 'Taskin Ahmed', 'image' => NULL, 'team_id' => 1, 'role' => 'Bowler', 'batting_style' => 'Left handed', 'bowling_style' => 'Right arm pace', 'born' => '2023-08-16 00:00:00', 'biography' => 'Taskin Ahmed', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 13, 'name' => 'Shoriful Islam', 'image' => NULL, 'team_id' => 1, 'role' => 'Bowler', 'batting_style' => 'Right handed', 'bowling_style' => 'Right arm pace', 'born' => '2023-08-11 00:00:00', 'biography' => 'Shoriful Islam', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 14, 'name' => 'Mustafizur Rahman', 'image' => NULL, 'team_id' => 1, 'role' => 'Bowler', 'batting_style' => 'Left handed', 'bowling_style' => 'Left arm pace', 'born' => '2023-08-11 00:00:00', 'biography' => 'Mustafizur Rahman', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 15, 'name' => 'Mohammad Naim', 'image' => NULL, 'team_id' => 1, 'role' => 'Batsman', 'batting_style' => 'Left handed', 'bowling_style' => 'N/A', 'born' => '2023-08-22 00:00:00', 'biography' => 'Mohammad Naim', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 16, 'name' => 'Najmul Hossain Shanto', 'image' => NULL, 'team_id' => 1, 'role' => 'Batsman', 'batting_style' => 'Left handed', 'bowling_style' => 'N/A', 'born' => '2023-08-16 00:00:00', 'biography' => 'Najmul Hossain Shanto', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 17, 'name' => 'Yasir Ali', 'image' => NULL, 'team_id' => 1, 'role' => 'Batsman', 'batting_style' => 'Right handed', 'bowling_style' => 'N/A', 'born' => '2023-08-16 00:00:00', 'biography' => 'Yasir Ali', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 18, 'name' => 'Dhawan, S', 'image' => NULL, 'team_id' => 2, 'role' => 'Batsman', 'batting_style' => 'Left handed', 'bowling_style' => 'N/A', 'born' => '2023-08-12 00:00:00', 'biography' => 'Dhawan, S', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 19, 'name' => 'Sharma, RG', 'image' => NULL, 'team_id' => 2, 'role' => 'Batsman', 'batting_style' => 'Right handed', 'bowling_style' => 'N/A', 'born' => '2023-08-16 00:00:00', 'biography' => 'Sharma, RG', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 20, 'name' => 'Shubman Gill', 'image' => NULL, 'team_id' => 2, 'role' => 'Batsman', 'batting_style' => 'Right handed', 'bowling_style' => 'N/A', 'born' => '2023-08-09 00:00:00', 'biography' => 'Shubman Gill', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 21, 'name' => 'Rahul, KL', 'image' => NULL, 'team_id' => 2, 'role' => 'WK Batsman', 'batting_style' => 'Right handed', 'bowling_style' => 'N/A', 'born' => '2023-08-18 00:00:00', 'biography' => 'Rahul, KL', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 22, 'name' => 'Ishan Kishan', 'image' => NULL, 'team_id' => 2, 'role' => 'WK Batsman', 'batting_style' => 'Right handed', 'bowling_style' => 'N/A', 'born' => '2023-08-17 00:00:00', 'biography' => 'Ishan Kishan', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 23, 'name' => 'Gaikwad, RD', 'image' => NULL, 'team_id' => 2, 'role' => 'Batsman', 'batting_style' => 'Right handed', 'bowling_style' => 'N/A', 'born' => '2023-08-16 00:00:00', 'biography' => 'Gaikwad, RD', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 24, 'name' => 'Iyer, SS', 'image' => NULL, 'team_id' => 2, 'role' => 'Batsman', 'batting_style' => 'Right handed', 'bowling_style' => 'N/A', 'born' => '2023-08-16 00:00:00', 'biography' => 'Iyer, SS', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 25, 'name' => 'Kohli, V', 'image' => NULL, 'team_id' => 2, 'role' => 'Batting AllRounder', 'batting_style' => 'Right handed', 'bowling_style' => 'Right arm pace', 'born' => '2023-08-17 00:00:00', 'biography' => 'Kohli, V', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 26, 'name' => 'Pant, RR', 'image' => NULL, 'team_id' => 2, 'role' => 'WK Batsman', 'batting_style' => 'Right handed', 'bowling_style' => 'N/A', 'born' => '2023-08-17 00:00:00', 'biography' => 'Pant, RR', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 27, 'name' => 'Patel, AR', 'image' => NULL, 'team_id' => 2, 'role' => 'Bowling AllRounder', 'batting_style' => 'Right handed', 'bowling_style' => 'Right arm spin', 'born' => '2023-08-18 00:00:00', 'biography' => 'Patel, AR', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 28, 'name' => 'Samson, SV', 'image' => NULL, 'team_id' => 2, 'role' => 'WK Batsman', 'batting_style' => 'Right handed', 'bowling_style' => 'N/A', 'born' => '2023-08-17 00:00:00', 'biography' => 'Samson, SV', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 29, 'name' => 'Jadeja, RA', 'image' => NULL, 'team_id' => 2, 'role' => 'Batting AllRounder', 'batting_style' => 'Left handed', 'bowling_style' => 'Left arm spin', 'born' => '2023-08-10 00:00:00', 'biography' => 'Jadeja, RA', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 30, 'name' => 'Chahal, YS', 'image' => NULL, 'team_id' => 2, 'role' => 'Bowler', 'batting_style' => 'Right handed', 'bowling_style' => 'Right arm spin', 'born' => '2023-08-17 00:00:00', 'biography' => 'Chahal, YS', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 31, 'name' => 'Pandya, HH', 'image' => NULL, 'team_id' => 2, 'role' => 'Bowling AllRounder', 'batting_style' => 'Right handed', 'bowling_style' => 'Right arm pace', 'born' => '2023-08-10 00:00:00', 'biography' => 'Pandya, HH', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 32, 'name' => 'Umran Malik', 'image' => NULL, 'team_id' => 2, 'role' => 'Bowler', 'batting_style' => 'Right handed', 'bowling_style' => 'Right arm pace', 'born' => '2023-08-10 00:00:00', 'biography' => 'Umran Malik', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 33, 'name' => 'Babar Azam', 'image' => NULL, 'team_id' => 3, 'role' => 'Batsman', 'batting_style' => 'Right handed', 'bowling_style' => 'N/A', 'born' => '2023-08-05 00:00:00', 'biography' => 'Babar Azam', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 34, 'name' => 'Imam-ul-Haq', 'image' => NULL, 'team_id' => 3, 'role' => 'WK Batsman', 'batting_style' => 'Right handed', 'bowling_style' => 'N/A', 'born' => '2023-08-09 00:00:00', 'biography' => 'Imam-ul-Haq', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 35, 'name' => 'Mohammad Rizwan', 'image' => NULL, 'team_id' => 3, 'role' => 'WK Batsman', 'batting_style' => 'Right handed', 'bowling_style' => 'N/A', 'born' => '2023-08-11 00:00:00', 'biography' => 'Mohammad Rizwan', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 36, 'name' => 'Shadab Khan', 'image' => NULL, 'team_id' => 3, 'role' => 'Batsman', 'batting_style' => 'Right handed', 'bowling_style' => 'N/A', 'born' => '2023-08-16 00:00:00', 'biography' => 'Shadab Khan', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 37, 'name' => 'Fakhar Zaman', 'image' => NULL, 'team_id' => 3, 'role' => 'Batting AllRounder', 'batting_style' => 'Right handed', 'bowling_style' => 'Right arm pace', 'born' => '2023-08-16 00:00:00', 'biography' => 'Fakhar Zaman', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 38, 'name' => 'Haris Rauf', 'image' => NULL, 'team_id' => 3, 'role' => 'Batting AllRounder', 'batting_style' => 'Right handed', 'bowling_style' => 'Left arm pace', 'born' => '2023-08-17 00:00:00', 'biography' => 'Haris Rauf', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 39, 'name' => 'Mohammad Nawaz', 'image' => NULL, 'team_id' => 3, 'role' => 'WK Batsman', 'batting_style' => 'Right handed', 'bowling_style' => 'Left arm pace', 'born' => '2023-08-17 00:00:00', 'biography' => 'Mohammad Nawaz', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 40, 'name' => 'Mohammad Wasim', 'image' => NULL, 'team_id' => 3, 'role' => 'Batting AllRounder', 'batting_style' => 'Right handed', 'bowling_style' => 'Right arm pace', 'born' => '2023-08-11 00:00:00', 'biography' => 'Mohammad Wasim', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 41, 'name' => 'Usama Mir', 'image' => NULL, 'team_id' => 3, 'role' => 'Bowling AllRounder', 'batting_style' => 'Right handed', 'bowling_style' => 'Left arm pace', 'born' => '2023-08-05 00:00:00', 'biography' => 'Usama Mir', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 42, 'name' => 'Kamran Ghulam', 'image' => NULL, 'team_id' => 3, 'role' => 'WK Batsman', 'batting_style' => 'Left handed', 'bowling_style' => 'Right arm pace', 'born' => '2023-08-11 00:00:00', 'biography' => 'Kamran Ghulam', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 43, 'name' => 'Khushdil Shah', 'image' => NULL, 'team_id' => 3, 'role' => 'Bowling AllRounder', 'batting_style' => 'Right handed', 'bowling_style' => 'Right arm pace', 'born' => '2023-08-16 00:00:00', 'biography' => 'Khushdil Shah', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 44, 'name' => 'de Silva, PWH', 'image' => NULL, 'team_id' => 4, 'role' => 'Batsman', 'batting_style' => 'Left handed', 'bowling_style' => 'Left arm pace', 'born' => '2023-08-30 00:00:00', 'biography' => 'de Silva, PWH', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 45, 'name' => 'Fernando, MNK', 'image' => NULL, 'team_id' => 4, 'role' => 'Bowling AllRounder', 'batting_style' => 'Left handed', 'bowling_style' => 'Left arm pace', 'born' => '2023-08-24 00:00:00', 'biography' => 'Fernando, MNK', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 46, 'name' => 'Hematha, MADI', 'image' => NULL, 'team_id' => 4, 'role' => 'Bowler', 'batting_style' => 'Left handed', 'bowling_style' => 'Left arm pace', 'born' => '2023-08-11 00:00:00', 'biography' => 'Hematha, MADI', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 47, 'name' => 'Kumara, CBRLS', 'image' => NULL, 'team_id' => 4, 'role' => 'Bowling AllRounder', 'batting_style' => 'Left handed', 'bowling_style' => 'Left arm pace', 'born' => '2023-08-12 00:00:00', 'biography' => 'Kumara, CBRLS', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 48, 'name' => 'Madushanka, D', 'image' => NULL, 'team_id' => 4, 'role' => 'Batting AllRounder', 'batting_style' => 'Right handed', 'bowling_style' => 'Right arm pace', 'born' => '2023-08-08 00:00:00', 'biography' => 'Madushanka, D', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 49, 'name' => 'Asalanka, KIC', 'image' => NULL, 'team_id' => 4, 'role' => 'Bowling AllRounder', 'batting_style' => 'Left handed', 'bowling_style' => 'Left arm pace', 'born' => '2023-08-24 00:00:00', 'biography' => 'Asalanka, KIC', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 50, 'name' => 'Chameera, PVD', 'image' => NULL, 'team_id' => 4, 'role' => 'Bowling AllRounder', 'batting_style' => 'Right handed', 'bowling_style' => 'Left arm pace', 'born' => '2023-09-06 00:00:00', 'biography' => 'Chameera, PVD', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 51, 'name' => 'de Silva, DM', 'image' => NULL, 'team_id' => 4, 'role' => 'WK Batsman', 'batting_style' => 'Right handed', 'bowling_style' => 'Right arm pace', 'born' => '2023-08-23 00:00:00', 'biography' => 'de Silva, DM', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 52, 'name' => 'Fernando, WIA', 'image' => NULL, 'team_id' => 4, 'role' => 'Bowling AllRounder', 'batting_style' => 'Right handed', 'bowling_style' => 'Right arm pace', 'born' => '2023-08-12 00:00:00', 'biography' => 'Fernando, WIA', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 53, 'name' => 'Karunaratne, C', 'image' => NULL, 'team_id' => 4, 'role' => 'Batting AllRounder', 'batting_style' => 'Left handed', 'bowling_style' => 'Right arm pace', 'born' => '2023-08-17 00:00:00', 'biography' => 'Karunaratne, C', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 54, 'name' => 'Mendis, BKG', 'image' => NULL, 'team_id' => 4, 'role' => 'Bowling AllRounder', 'batting_style' => 'Right handed', 'bowling_style' => 'Right arm pace', 'born' => '2023-08-23 00:00:00', 'biography' => 'Mendis, BKG', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ];
        DB::table('players')->insert($players);
    }
}
